CREATE TABLE ACCOUNTS (
  AccountID NUMBER PRIMARY KEY,
  CustomerID NUMBER,
  AccountType VARCHAR2(20), 
  Balance NUMBER(10, 2)
);

INSERT INTO ACCOUNTS VALUES (1, 1, 'Savings', 1000);
INSERT INTO ACCOUNTS VALUES (2, 1, 'Checking', 500);
INSERT INTO ACCOUNTS VALUES (3, 2, 'Savings', 2000);
INSERT INTO ACCOUNTS VALUES (4, 2, 'Checking', 1000);

CREATE TABLE EMPLOYEES (
  EmployeeID NUMBER PRIMARY KEY,
  Name VARCHAR2(50),
  Department VARCHAR2(50),
  Salary NUMBER(10, 2)
);

INSERT INTO EMPLOYEES VALUES (1, 'Alice', 'Sales', 5000);
INSERT INTO EMPLOYEES VALUES (2, 'Bob', 'Sales', 5500);
INSERT INTO EMPLOYEES VALUES (3, 'Charlie', 'HR', 6000);



COMMIT;

