CREATE TABLE CUSTOMERS (
  CustomerID NUMBER PRIMARY KEY,
  Name VARCHAR2(50),
  Age NUMBER,
  Balance NUMBER(10, 2),
  IsVIP CHAR(1) DEFAULT 'N'
);

CREATE TABLE LOANS (
  LoanID NUMBER PRIMARY KEY,
  CustomerID NUMBER,
  InterestRate NUMBER(5, 2),
  DueDate DATE
);

INSERT INTO CUSTOMERS VALUES (1, 'Alice', 65, 15000, 'N');
INSERT INTO CUSTOMERS VALUES (2, 'Bob', 45, 5000, 'N');
INSERT INTO CUSTOMERS VALUES (3, 'Charlie', 70, 12000, 'N');

INSERT INTO LOANS VALUES (1, 1, 5.5, SYSDATE + 20);
INSERT INTO LOANS VALUES (2, 2, 6.0, SYSDATE + 40);
INSERT INTO LOANS VALUES (3, 3, 4.5, SYSDATE + 10);

COMMIT;

SELECT * FROM CUSTOMERS;
SELECT * FROM LOANS;

